from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
import uuid
from pydantic import BaseModel, Field

DEFAULT_LEGAL_DISCLAIMER = (
    "LEGAL DISCLAIMER: This Pre-Clearance Intelligence Report is generated by automated multi-agent "
    "analysis for operational clearance-workflow and preliminary risk evaluation purposes only. "
    "This report DOES NOT constitute legal advice, a formal legal opinion, or an errors & omissions (E&O) "
    "insurance binder. All risk scores, verification decisions, and resolution recommendations should be "
    "reviewed and confirmed by qualified entertainment legal counsel prior to commercial distribution or broadcast."
)

class ReportStatus(str, Enum):
    GENERATING = "GENERATING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"

class ReportFormat(str, Enum):
    JSON = "JSON"
    HTML = "HTML"
    PDF = "PDF"

class ReportSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"

class ReportFinding(BaseModel):
    """
    Consolidated, cross-stage intelligence finding for an entity.
    Traces the entire 7-stage evidence pipeline:
    FRAME -> ENTITY -> EVIDENCE -> RESEARCH -> RISK -> VERIFICATION -> RESOLUTION
    """
    entity_id: str
    entity_name: str
    entity_type: str
    classification: str
    risk_level: str
    risk_score: float = 0.0
    risk_factors: List[str] = Field(default_factory=list)
    scene_number: Optional[int] = None
    timestamp_start: Optional[float] = None
    timestamp_end: Optional[float] = None
    rights_holder: Optional[str] = None
    
    # Verification intelligence
    verification_decision: Optional[str] = None
    verification_confidence: Optional[float] = None
    verification_rationale: Optional[str] = None
    
    # Resolution intelligence
    resolution_status: Optional[str] = None
    resolution_action: Optional[str] = None
    resolution_priority: Optional[str] = None
    resolution_owner: Optional[str] = None
    resolution_cost_estimate: Optional[str] = None
    resolution_time_estimate: Optional[str] = None
    resolution_details: Optional[str] = None
    
    # Evidence traceability
    evidence_count: int = 0
    evidence_snippets: List[Dict[str, Any]] = Field(default_factory=list)
    evidence_chain: Dict[str, Any] = Field(default_factory=dict)
    
    metadata: Dict[str, Any] = Field(default_factory=dict)

class ReportResult(BaseModel):
    """
    Phase 8 comprehensive multi-format clearance intelligence report.
    """
    report_id: str = Field(default_factory=lambda: f"rep_{uuid.uuid4().hex[:12]}")
    production_id: str
    job_id: str
    production_title: str = ""
    version: str = "1.0"
    status: ReportStatus = ReportStatus.COMPLETED
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    generation_duration_ms: float = 0.0
    
    # Dynamic counts & coverage
    total_entities: int = 0
    researched_count: int = 0
    verified_count: int = 0
    resolved_count: int = 0
    research_coverage: float = 0.0
    verification_coverage: float = 0.0
    resolution_coverage: float = 0.0
    
    # Distributions
    classification_counts: Dict[str, int] = Field(default_factory=dict)
    risk_distribution: Dict[str, int] = Field(default_factory=dict)
    verification_distribution: Dict[str, int] = Field(default_factory=dict)
    resolution_distribution: Dict[str, int] = Field(default_factory=dict)
    
    # Consolidated Findings
    priority_findings: List[ReportFinding] = Field(default_factory=list)
    visual_only_findings: List[ReportFinding] = Field(default_factory=list)
    all_findings: List[ReportFinding] = Field(default_factory=list)

    # Parallel Research Intelligence (Complete factual research evidence & lineage)
    parallel_research_intelligence: List[Dict[str, Any]] = Field(default_factory=list)

    # Phase 10: Financial Exposure Intelligence
    financial_exposure_intelligence: List[Dict[str, Any]] = Field(default_factory=list)

    # Phase 11: Clearance Outreach Agent (Permission Request Drafts)
    clearance_outreach_drafts: List[Dict[str, Any]] = Field(default_factory=list)

    # Phase 12: Visual Remediation Studio (Proposed frame cleanups & replacements)
    visual_remediation_proposals: List[Dict[str, Any]] = Field(default_factory=list)
    
    # Formats & artifacts
    formats: List[ReportFormat] = Field(default_factory=lambda: [ReportFormat.JSON, ReportFormat.HTML, ReportFormat.PDF])
    format_paths: Dict[str, str] = Field(default_factory=dict)
    format_urls: Dict[str, str] = Field(default_factory=dict)
    format_errors: Dict[str, str] = Field(default_factory=dict)
    
    executive_summary: str = ""
    disclaimer: str = DEFAULT_LEGAL_DISCLAIMER
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @property
    def id(self) -> str:
        return self.report_id

    @property
    def title(self) -> str:
        return f"Chain of Title Pre-Clearance Intelligence Report: {self.production_title or self.production_id} (v{self.version})"

    @property
    def visual_only_count(self) -> int:
        return self.classification_counts.get("VISUAL_ONLY", 0)

    @property
    def script_only_count(self) -> int:
        return self.classification_counts.get("SCRIPT_ONLY", 0)

    @property
    def both_count(self) -> int:
        return self.classification_counts.get("BOTH", 0)

    @property
    def audio_only_count(self) -> int:
        return self.classification_counts.get("AUDIO_ONLY", 0)

    @property
    def high_risk_count(self) -> int:
        return self.risk_distribution.get("HIGH", 0)

    @property
    def medium_risk_count(self) -> int:
        return self.risk_distribution.get("MEDIUM", 0)

    @property
    def low_risk_count(self) -> int:
        return self.risk_distribution.get("LOW", 0)

    @property
    def unresolved_count(self) -> int:
        return self.resolution_distribution.get("UNRESOLVED", 0) or (self.high_risk_count + self.medium_risk_count)

    @property
    def pdf_path(self) -> Optional[str]:
        return self.format_paths.get("PDF") or self.format_paths.get("pdf")

# Backward-compatibility legacy Report model
class Report(BaseModel):
    id: str = Field(default_factory=lambda: f"rep_{uuid.uuid4().hex[:10]}")
    production_id: str
    job_id: str
    title: str = "Chain of Title Pre-Clearance Intelligence Report"
    executive_summary: str = ""
    total_entities: int = 0
    visual_only_count: int = 0
    script_only_count: int = 0
    both_count: int = 0
    audio_only_count: int = 0
    high_risk_count: int = 0
    medium_risk_count: int = 0
    low_risk_count: int = 0
    unresolved_count: int = 0
    entity_breakdown: List[Dict[str, Any]] = Field(default_factory=list)
    clearance_checklist: List[Dict[str, Any]] = Field(default_factory=list)
    pdf_path: Optional[str] = None
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = Field(default_factory=dict)
    
    # Enhanced Phase 8 fields on Report model for backward compatibility
    report_result: Optional[ReportResult] = None
